services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=train
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
    ports:
      - "5432:5432"
    networks:
      - my_network
  spring-bk:
    build:
      context: .
      dockerfile: ../../reservation train/backend/demo/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/train
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
